import React from 'react'
//  import { connect } from 'react-redux'
//  import RegisterUserComponent from './RegisterUserComponent'
//  import { IState } from '../reducers'
//  import {} from '../../action-mappers'